import React, { useState } from 'react';
import { BrowserRouter as Router, Routes, Route, Link, Navigate, useLocation } from 'react-router-dom';
import { AuthProvider, useAuth } from './context/AuthContext';
import ProtectedRoute from './components/ProtectedRoute';
import CitizenDashboard from './portals/citizen/CitizenDashboard';
import ConsentCenter from './portals/citizen/ConsentCenter';
import PoliceDashboard from './portals/police/PoliceDashboard';
import {
  ShieldAlert, LogOut, Eye, User, Lock, Mail, Shield, Building,
  Key, CheckCircle2, ChevronRight, Menu, X
} from 'lucide-react';

// --- LOGIN & REGISTER COMPONENT ---
const LoginPortal = () => {
  const { login, register, isMfaRequired, verifyMfaLogin, cancelMfaPrompt } = useAuth();
  const [isRegister, setIsRegister] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  // Form states
  const [username, setUsername] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [role, setRole] = useState('citizen');
  const [badgeNumber, setBadgeNumber] = useState('');
  const [department, setDepartment] = useState('');
  const [mfaCode, setMfaCode] = useState('');

  const { user } = useAuth();

  // If already logged in, redirect to respective dashboard
  if (user) {
    return <Navigate to={user.role === 'police' ? '/police/dashboard' : '/citizen/dashboard'} replace />;
  }

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setSuccess('');

    try {
      if (isRegister) {
        await register(username, email, password, role, badgeNumber, department);
        setSuccess('Registration completed! Please sign in.');
        setIsRegister(false);
        setPassword('');
      } else {
        const res = await login(username, password);
        if (res?.mfa_required) {
          setMfaCode('');
        }
      }
    } catch (err) {
      setError(err);
    }
  };

  const handleMfaSubmit = async (e) => {
    e.preventDefault();
    setError('');
    try {
      await verifyMfaLogin(mfaCode);
    } catch (err) {
      setError(err);
    }
  };

  return (
    <div className="min-h-[85vh] flex items-center justify-center p-4">
      <div className="glass-panel-heavy w-full max-w-md p-8 rounded-3xl shadow-2xl border border-white/10 space-y-6">
        
        {/* Logo and Headings */}
        <div className="text-center space-y-2">
          <div className="inline-flex p-3 rounded-2xl bg-indigo-500/10 border border-indigo-500/20 text-indigo-400">
            <ShieldAlert className="w-8 h-8 animate-pulse" />
          </div>
          <h2 className="text-2xl font-bold text-white tracking-wider font-sans">NETRA SURVEILLANCE</h2>
          <p className="text-xs text-gray-400">Privacy-First AI Community Protection Network</p>
        </div>

        {isMfaRequired ? (
          /* MFA Prompt Code Form */
          <form onSubmit={handleMfaSubmit} className="space-y-4">
            <div className="space-y-2 text-center">
              <h3 className="text-sm font-semibold text-white">MFA Authentication Required</h3>
              <p className="text-xs text-gray-400">Enter the 6-digit passcode generated by your TOTP Authenticator application.</p>
            </div>

            {error && (
              <div className="p-3 rounded-xl bg-red-500/10 border border-red-500/20 text-red-400 text-xs">
                {error}
              </div>
            )}

            <div className="space-y-2">
              <label className="text-xs font-semibold text-gray-300 flex items-center gap-1.5">
                <Key className="w-3.5 h-3.5 text-amber-500" /> Authenticator Token
              </label>
              <input
                type="text" required placeholder="000 000" maxLength={6} value={mfaCode}
                onChange={(e) => setMfaCode(e.target.value)}
                className="w-full text-center tracking-widest font-mono text-lg px-4 py-2.5 rounded-xl bg-black/40 border border-white/10 text-white outline-none focus:border-indigo-500"
              />
            </div>

            <div className="flex gap-3 pt-2">
              <button
                type="submit"
                className="flex-1 py-2.5 bg-amber-500 hover:bg-amber-600 text-gray-950 font-bold rounded-xl text-xs transition-all shadow-glowGreen"
              >
                Validate and Login
              </button>
              <button
                type="button" onClick={cancelMfaPrompt}
                className="px-4 py-2.5 bg-white/5 hover:bg-white/10 text-white font-semibold rounded-xl text-xs transition-all"
              >
                Cancel
              </button>
            </div>
          </form>
        ) : (
          /* Normal Sign-In / Registration Form */
          <form onSubmit={handleSubmit} className="space-y-4">
            {error && (
              <div className="p-3 rounded-xl bg-red-500/10 border border-red-500/20 text-red-400 text-xs">
                {error}
              </div>
            )}
            
            {success && (
              <div className="p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-xs flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4" /> {success}
              </div>
            )}

            {/* Role switch in registration */}
            {isRegister && (
              <div className="grid grid-cols-2 gap-2 bg-black/40 p-1 rounded-xl border border-white/5">
                <button
                  type="button" onClick={() => setRole('citizen')}
                  className={`py-1.5 rounded-lg text-xs font-semibold transition-all ${
                    role === 'citizen' ? 'bg-indigo-500 text-white' : 'text-gray-400 hover:text-white'
                  }`}
                >
                  Citizen Profile
                </button>
                <button
                  type="button" onClick={() => setRole('police')}
                  className={`py-1.5 rounded-lg text-xs font-semibold transition-all ${
                    role === 'police' ? 'bg-indigo-500 text-white' : 'text-gray-400 hover:text-white'
                  }`}
                >
                  Police Officer
                </button>
              </div>
            )}

            <div className="space-y-3 text-xs">
              <div className="space-y-1.5">
                <label className="text-gray-300 font-semibold flex items-center gap-1">
                  <User className="w-3.5 h-3.5 text-gray-500" /> Username
                </label>
                <input
                  type="text" required placeholder="e.g. johndoe" value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  className="w-full px-3.5 py-2.5 rounded-xl bg-black/40 border border-white/10 text-white placeholder-gray-600 focus:border-indigo-500 outline-none"
                />
              </div>

              {isRegister && (
                <div className="space-y-1.5">
                  <label className="text-gray-300 font-semibold flex items-center gap-1">
                    <Mail className="w-3.5 h-3.5 text-gray-500" /> Email Address
                  </label>
                  <input
                    type="email" required placeholder="john@example.com" value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    className="w-full px-3.5 py-2.5 rounded-xl bg-black/40 border border-white/10 text-white placeholder-gray-600 focus:border-indigo-500 outline-none"
                  />
                </div>
              )}

              {/* Police Specific input fields */}
              {isRegister && role === 'police' && (
                <div className="grid grid-cols-2 gap-3">
                  <div className="space-y-1.5">
                    <label className="text-gray-300 font-semibold flex items-center gap-1">
                      <Shield className="w-3.5 h-3.5 text-gray-500" /> Badge Number
                    </label>
                    <input
                      type="text" required placeholder="Badge ID" value={badgeNumber}
                      onChange={(e) => setBadgeNumber(e.target.value)}
                      className="w-full px-3.5 py-2.5 rounded-xl bg-black/40 border border-white/10 text-white placeholder-gray-600 focus:border-indigo-500 outline-none"
                    />
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-gray-300 font-semibold flex items-center gap-1">
                      <Building className="w-3.5 h-3.5 text-gray-500" /> Department
                    </label>
                    <input
                      type="text" required placeholder="SFPD Central" value={department}
                      onChange={(e) => setDepartment(e.target.value)}
                      className="w-full px-3.5 py-2.5 rounded-xl bg-black/40 border border-white/10 text-white placeholder-gray-600 focus:border-indigo-500 outline-none"
                    />
                  </div>
                </div>
              )}

              <div className="space-y-1.5">
                <label className="text-gray-300 font-semibold flex items-center gap-1">
                  <Lock className="w-3.5 h-3.5 text-gray-500" /> Password
                </label>
                <input
                  type="password" required placeholder="••••••••" value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="w-full px-3.5 py-2.5 rounded-xl bg-black/40 border border-white/10 text-white placeholder-gray-600 focus:border-indigo-500 outline-none"
                />
              </div>
            </div>

            <button
              type="submit"
              className="w-full py-3 bg-indigo-500 hover:bg-indigo-600 text-white font-bold rounded-xl text-xs transition-all shadow-glowIndigo mt-2"
            >
              {isRegister ? 'Create Secure Account' : 'Authenticate Credentials'}
            </button>

            <div className="text-center pt-2">
              <button
                type="button" onClick={() => { setIsRegister(!isRegister); setError(''); }}
                className="text-xs text-indigo-400 hover:underline inline-flex items-center gap-0.5"
              >
                {isRegister ? 'Already registered? Sign In' : 'Create new Citizen/Police account'} <ChevronRight className="w-3 h-3" />
              </button>
            </div>
          </form>
        )}
      </div>
    </div>
  );
};

// --- APP LAYOUT COMPONENT ---
const AppLayout = () => {
  const { user, logout } = useAuth();
  const location = useLocation();
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  const isActive = (path) => location.pathname === path;

  return (
    <div className="min-h-screen flex flex-col">
      {/* Header bar */}
      <header className="glass-panel border-b border-white/5 sticky top-0 z-40 backdrop-blur-md">
        <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
          {/* Logo */}
          <Link to="/" className="flex items-center gap-2 select-none group">
            <div className="p-2 rounded-xl bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 group-hover:scale-105 transition-transform">
              <ShieldAlert className="w-5 h-5 animate-pulse" />
            </div>
            <span className="font-extrabold tracking-wider text-sm text-white">NETRA</span>
          </Link>

          {/* Navigation Links */}
          {user && (
            <>
              {/* Desktop Nav */}
              <nav className="hidden md:flex items-center gap-1.5 text-xs font-semibold">
                {user.role === 'citizen' ? (
                  <>
                    <Link
                      to="/citizen/dashboard"
                      className={`px-4 py-2 rounded-lg transition-colors ${
                        isActive('/citizen/dashboard') ? 'bg-indigo-500/10 text-indigo-400 border border-indigo-500/15' : 'text-gray-300 hover:bg-white/5'
                      }`}
                    >
                      Surveillance Nodes
                    </Link>
                    <Link
                      to="/citizen/consent"
                      className={`px-4 py-2 rounded-lg transition-colors ${
                        isActive('/citizen/consent') ? 'bg-indigo-500/10 text-indigo-400 border border-indigo-500/15' : 'text-gray-300 hover:bg-white/5'
                      }`}
                    >
                      Consent Center
                    </Link>
                  </>
                ) : (
                  <Link
                    to="/police/dashboard"
                    className={`px-4 py-2 rounded-lg transition-colors ${
                      isActive('/police/dashboard') ? 'bg-indigo-500/10 text-indigo-400 border border-indigo-500/15' : 'text-gray-300 hover:bg-white/5'
                    }`}
                  >
                    Tactical Operations
                  </Link>
                )}
              </nav>

              {/* User profile actions */}
              <div className="hidden md:flex items-center gap-4">
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-full bg-white/5 border border-white/10 flex items-center justify-center text-xs font-bold text-indigo-400 uppercase">
                    {user.username.slice(0, 2)}
                  </div>
                  <div className="flex flex-col text-left">
                    <span className="text-xs font-bold text-white">@{user.username}</span>
                    <span className="text-[10px] text-indigo-400 font-semibold uppercase">{user.role}</span>
                  </div>
                </div>
                <button
                  onClick={logout}
                  className="p-2 rounded-xl bg-red-500/5 hover:bg-red-500 text-red-400 hover:text-white transition-all border border-red-500/10"
                  title="Sign Out"
                >
                  <LogOut className="w-4 h-4" />
                </button>
              </div>

              {/* Mobile menu trigger */}
              <button
                onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
                className="md:hidden p-2 rounded-lg bg-white/5 text-gray-300 hover:text-white"
              >
                {mobileMenuOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
              </button>
            </>
          )}
        </div>

        {/* Mobile menu panel */}
        {user && mobileMenuOpen && (
          <div className="md:hidden border-t border-white/5 bg-[#0B0F19] p-4 space-y-3">
            <div className="flex items-center gap-3 pb-3 border-b border-white/5">
              <div className="w-10 h-10 rounded-full bg-white/5 border border-white/10 flex items-center justify-center font-bold text-indigo-400 uppercase">
                {user.username.slice(0, 2)}
              </div>
              <div className="flex flex-col text-left">
                <span className="text-xs font-bold text-white">@{user.username}</span>
                <span className="text-[10px] text-indigo-400 font-semibold uppercase">{user.role}</span>
              </div>
            </div>

            <nav className="flex flex-col gap-1 text-xs font-semibold">
              {user.role === 'citizen' ? (
                <>
                  <Link
                    to="/citizen/dashboard"
                    onClick={() => setMobileMenuOpen(false)}
                    className={`p-2.5 rounded-lg transition-colors ${
                      isActive('/citizen/dashboard') ? 'bg-indigo-500/10 text-indigo-400' : 'text-gray-300 hover:bg-white/5'
                    }`}
                  >
                    Surveillance Nodes
                  </Link>
                  <Link
                    to="/citizen/consent"
                    onClick={() => setMobileMenuOpen(false)}
                    className={`p-2.5 rounded-lg transition-colors ${
                      isActive('/citizen/consent') ? 'bg-indigo-500/10 text-indigo-400' : 'text-gray-300 hover:bg-white/5'
                    }`}
                  >
                    Consent Center
                  </Link>
                </>
              ) : (
                <Link
                  to="/police/dashboard"
                  onClick={() => setMobileMenuOpen(false)}
                  className={`p-2.5 rounded-lg transition-colors ${
                    isActive('/police/dashboard') ? 'bg-indigo-500/10 text-indigo-400' : 'text-gray-300 hover:bg-white/5'
                  }`}
                >
                  Tactical Operations
                </Link>
              )}
            </nav>

            <button
              onClick={() => { logout(); setMobileMenuOpen(false); }}
              className="w-full py-2.5 rounded-xl bg-red-500/10 hover:bg-red-500 text-red-400 hover:text-white transition-all text-xs font-bold border border-red-500/10 flex items-center justify-center gap-1.5"
            >
              <LogOut className="w-4 h-4" /> Sign Out
            </button>
          </div>
        )}
      </header>

      {/* Main Container */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 py-8">
        <Routes>
          <Route path="/login" element={<LoginPortal />} />
          
          {/* Citizen Routes */}
          <Route element={<ProtectedRoute allowedRoles={['citizen', 'admin']} />}>
            <Route path="/citizen/dashboard" element={<CitizenDashboard />} />
            <Route path="/citizen/consent" element={<ConsentCenter />} />
          </Route>

          {/* Police Routes */}
          <Route element={<ProtectedRoute allowedRoles={['police', 'admin']} />}>
            <Route path="/police/dashboard" element={<PoliceDashboard />} />
          </Route>

          {/* Catch-all redirects */}
          <Route
            path="*"
            element={<Navigate to={user ? (user.role === 'police' ? '/police/dashboard' : '/citizen/dashboard') : '/login'} replace />}
          />
        </Routes>
      </main>

      {/* Footer copyright */}
      <footer className="py-6 border-t border-white/5 text-center text-[10px] text-gray-500">
        &copy; {new Date().getFullYear()} Netra Security Systems Corp. Decentralized and Preserving Community Civil Liberties.
      </footer>
    </div>
  );
};

const App = () => {
  return (
    <Router>
      <AuthProvider>
        <AppLayout />
      </AuthProvider>
    </Router>
  );
};

export default App;
